Myblog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns =[
    url(r'^$', views.homepage, name='homepage'),
    url(r'^article/$', views.article, name='article'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^about/$', views.about, name='about' ),
    url(r'^article/(?P<pk>\d+)/detail/$', views.article_detail, name='detail'),
    url(r'^article/(?P<pk>\d+)/edit/$', views.edit, name='edit'),
    url(r'^singup/$', views.signup, name='signup'),
    url(r'^login/$', views.login, name='login'),
    url(r'^set_password/$',views.set_password, name='set_password'),
    url(r'^log_oug/$', views.log_out, name='log_out'),
    url(r'^add/$', views.add,name='add'),
    url(r'^article/(?P<pk>\d+)/comment/$', views.add_comment, name='add_comment'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^article/(?P<pk>\d+)/delete/$', views.delete, name= 'delete'),




]

blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length=128)
    email = models.EmailField()

    class Meta:
        ordering =['name']

    def __str__(self):
        return self.name

class Categoty(models.Model):
    category_name = models.CharField(max_length=128)
    category_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering =['category_name']

    def __str__(self):
        return self.category_name

# class Tag(models.Model):
#     tag_name = models.CharField(max_length=128)
#     create_date = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return self.tag_name

class Article(models.Model):
    title = models.CharField(max_length=128)
    pubdate = models.DateTimeField()
    text = models.TextField()
    update = models.DateTimeField()
    author = models.ForeignKey(Author)
    category = models.ForeignKey(Categoty)
    # tags = models.ManyToManyField(Tag)

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

class Comment(models.Model):
    article = models.ForeignKey(Article, related_name='comments')
    author = models.CharField(max_length=128)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now=True)
    approved_comment = models.BooleanField(default=False)


    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import *

class EditForm(forms.ModelForm):
    # title = forms.CharField(max_length=128)
    # author = forms.CharField(max_length=128)
    # text = forms.Textarea()
    # text = forms.CharField(widget=forms.Textarea)
    # category = forms.CharField(max_length=128)

    class Meta:
        model = Article
        fields = ('title','text','author','category','pubdate','update',)


# class ContactForm(forms.ModelForm):
#     subject = forms.CharField(max_length=128)
#     message = forms.CharField(widget=forms.Textarea)
#     sender = forms.EmailField()

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text',)


class ContactForm(forms.Form):
    name = forms.CharField(max_length=128, required=True)
    email = forms.EmailField(required=True)
    content = forms.CharField(
        widget=forms.Textarea,
        required=True
    )
    subject = forms.CharField(max_length=128, required=True)

    # def __init__(self, *args, **kwargs):
    #     super(ContactForm, self).__init__(*args, **kwargs)
    #     self.fields['name'].label = 'Your name:'
    #     self.fields['email'].label = 'Your email:'
    #     self.fields['content'].label = 'Say something.'
    #     self.fields['subject'].label = 'Subject:'

blog/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from django.http import HttpResponseRedirect
from .forms import *
from django.core.urlresolvers import reverse
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
# Create your views here.
def homepage(request):
    article = Article.objects.all()
    user = request.user if request.user.is_authenticated() else None

    content={
        'user':user,
        'active_menu': 'homepage',
    }

    return  render(request, 'blog/homepage.html', content)


def article(request):
    article = Article.objects.all()

    category = Categoty.objects.all()


    paginator = Paginator(article, 3)

    page = request.GET.get('page')

    try:
        article_page = paginator.page(page)
    except PageNotAnInteger:
        article_page = paginator.page(1)
    except EmptyPage:
        article_page = paginator.page(paginator.num_pages)


    content ={

        'article_page': article_page,
        'paginator': paginator,
        'category': category,
        'active_menu':'articlepage',


    }

    return render(request, 'blog/article.html', content)

def contact(request):

    form = ContactForm()

    if request.method =="POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name', '')
            email = request.POST.get('email','')
            message = request.POST.get('content','')
            subject = request.POST.get('subject','')
            send_mail(
                (name, subject),
                message,
                email,
                ['neon@gmail.com'],
                fail_silently=True,
            )
            return redirect('contact')




    content={
        'active_menu': 'contactpage',
        'form': form,
    }


    return render(request, 'blog/contact.html', content)



def about(request):



    content={
        'active_menu': 'aboutpage',
    }


    return render(request, 'blog/about.html', content)


def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            return redirect('detail', pk=article.pk)

    else:
        form = CommentForm()

    content ={
        'article': article,
        'form':form,
    }


    return render(request, 'blog/article_detail.html',content)

def edit(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = EditForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect( 'detail', pk=article.pk)
    else:
        form = EditForm(instance=article)
    return render(request, 'blog/edit.html', {'form':form})

def signup(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('homepage'))
    state = None
    if request.method == "POST":
        password = request.POST.get('password','')
        repeat_password = request.POST.get('repeat_password','')
        if password == '' or repeat_password == '':
            state = 'empty'
        elif password != repeat_password:
            state = 'repeat_error'
        else:
            username = request.POST.get('username','')
            if User.objects.filter(username=username):
                state = 'user_exist'
            else:
                new_user = User.objects.create_user(password=password,username=username,
                                                    email=request.POST.get('email',''))
                new_user.save()
                state = 'success'
    content = {
        'state':state,
        'user': None,
    }
    return render(request, 'blog/signup.html', content)

def login(request):
    if request.user.is_authenticated():
        return  HttpResponseRedirect(reverse('homepage'))
    state = None

    if request.method == 'POST':
        password = request.POST.get('password','')
        username = request.POST.get('username','')
        user = auth.authenticate(password=password,username=username)
        if user is not None:
            auth.login(request,user)
            return HttpResponseRedirect(reverse('homepage'))
        else:
            state = 'not_exist_or_password_error'

    content ={
        'state': state,
        'user': None,
    }
    return render(request, 'blog/login.html', content)

@login_required
def set_password(request):
    user = request.user
    state = None
    if request.method == 'POST':
        old_password = request.POST.get('old_password','')
        new_password = request.POST.get('new_password','')
        repeat_password = request.POST.get('repeat_password','')
        if user.check_password(old_password):
            if not new_password:
                state='empty'
            elif new_password != repeat_password:
                state = 'repeat_error'
            elif new_password == old_password:
                state = 'password_same'
            else:
                user.set_password(new_password)
                user.save()
                state = 'success'
        else:
            state = 'password_error'
    content = {
        'user': user,
        'state': state,
    }
    return render(request, 'blog/set_password.html',content)

def log_out(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('homepage'))


def add(request):
    if request.method == 'POST':
        form = EditForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('article'))
    else:
        form = EditForm()
    return render(request,'blog/add.html',{'form':form})

def add_comment(request,pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()
            return redirect('detail', pk=article.pk)

    else:
        form = CommentForm()
    return render(request, 'blog/add_comment.html', {'form':form})

@login_required
def comment_approve(request,pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('detail',pk=comment.article.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('detail',pk=comment.article.pk)


def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.delete()
    return redirect('article')

templates/blog/about.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}Watch{% endblock %}





{% block content %}



    <div class="jumbotron" id="about-text" >
        <div class="container text-center">


{#            <h1>Hello.</h1>#}
{#            <h3>&emsp;&emsp;World.</h3>#}

        </div>
    </div>









    <div class="container">
        <h1>Creative</h1>
        <h2>Passion</h2>
    </div>


































{% endblock %}

templates/blog/add.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}Add Article{% endblock %}


{% block content %}


    <div class="jumbotron" id="add-text" >
        <div class="container text-center">
            <h1>Article</h1>
            <h3>&emsp;&emsp;Adding.</h3>

        </div>
    </div>

    <form method="POST" class="center-block">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                {{ form.as_p }}
                <button type="submit" class=" btn btn-default">Summit</button>
            </div>
        </div>


    </form>
{% endblock %}

templates/blog/add_comment.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}Add comment{% endblock %}





{% block content %}

    <div class="jumbotron" id="addcomment-text" >
        <div class="container text-center">
            <h1>Article</h1>
            <h3>&emsp;&emsp;wondering.</h3>

        </div>
    </div>



    <h1>New comment</h1>
{#    <form method="POST" class="post-form">#}
{#        {% csrf_token %}#}
{#        {{ form.as_p }}#}
{#        <button type="submit" class="save btn btn-default">Send</button>#}
{#    </form>#}


    <div class="container">
            <div class="row">
                <div class="col-sm-4">
                <h3>Drop me a line!</h3>
            <hr>
        <address>
        <strong>Email:</strong> <a href="mailto:#"> neon@domain.com</a><br><br>
        <strong>Phone:</strong> 1983
        </address>
            </div>

    <div class="col-sm-8 contact-form">

        <form id="contact" method="post" class="form" role="form">
             {% csrf_token %}
                <div class="row">
                <div class="col-xs-6 col-md-6 form-group">
                <input class="form-control" id="name" name="author" placeholder="Title" type="text" required autofocus />
            </div>
{#        <div class="col-xs-6 col-md-6 form-group">#}
{#            <input class="form-control" id="email" name="email" placeholder="Email" type="email" required />#}
{#        </div>#}
            </div>
        <textarea class="form-control" id="message" name="text" placeholder="Text" rows="5"></textarea>
        <br />
        <div class="row">

        <div class="col-xs-12 col-md-12 form-group">
        <button class="btn btn-primary pull-right" type="submit">Submit</button>
        </div>
        </div>
        </form>
    </div>
</div>
    </div>
{% endblock %}

templates/blog/article.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}Article{% endblock %}





{% block content %}

    <div class="jumbotron" id="text-base" >
        <div class="container text-center">
{#            <h1 class="title">Hello</h1>#}
{#            <h3 class="title">&emsp;&emsp;World.</h3>#}

        </div>
    </div>



    <div class="container">

      <div class="header text-center">
{#          <div class="row">#}

              <div class="col-md-3 col-md-offset-2 title">
                  <h1>
                  <div class="well">Blog  <small class="title">Article</small></div>
{#                  <p class="lead blog-description">GG</p>#}
                      </h1>
              </div>
          <div class="col-md-2 ">
                  <h1 class="title">
                      {% if user.is_authenticated %}
                      <a href="{% url 'add' %}"><span class="glyphicon glyphicon-plus-sign"> </span></a>
                      {% endif %}
                  </h1>
                </div>
              <div class="col-md-2 col-md-offset-4">

              </div>
          </div>

      </div>

{#      <div class="blog-header">#}
{#        <h1 class="blog-title">The Bootstrap Blog</h1>#}
{#        <p class="lead blog-description">The official </p>#}
{#      </div>#}








    <div class="container">
    <div class="row">
        <div class="col-sm-8">
            {% for article in article_page %}
            <div class="panel panel-white post panel-shadow">
                <div class="post-heading">
                    <div class="pull-left image">
{#                        <img src="#" alt="user profile image">#}
                        <span class="glyphicon glyphicon-tree-deciduous"></span>
                    </div>
                    <div class="pull-left meta">
                        <div class="title h5">
                            <h2><a href="{% url 'detail' pk=article.pk %}">{{ article.title }}</a> </h2>
                            <a href="{% url 'about' %}"><b>{{ article.author.name }}</b></a>
                        </div>
                        <h6 class="text-muted time">{{ article.pubdate }}</h6>
                    </div>
                </div>
            <div class="post-description">
                    <p>{{ article.text }}</p>
                <div class="stats">
{#                        <a href="#" class="btn btn-default stat-item">#}
{#                            <span class="glyphicon glyphicon-thumbs-up"></span> 2#}
{#                        </a>#}
{#                        <a href="#" class="btn btn-default stat-item">#}
{#                            <span class="glyphicon glyphicon-thumbs-down"></span> 12#}
{#                        </a>#}
                    <a href="{% url 'detail' pk=article.pk %}">Comments:{{ article.approved_comments.count }}</a>

                </div>
            </div>
        </div>

        {% endfor %}




          <nav>
            <ul class="pager">
                {% if article_page.has_previous %}
              <li><a href="?page={{ article_page.previous_page_number }}">Previous</a></li>
                {% else %}
                <li><a href="#">Previous</a></li>
                {% endif %}
              <span class="current">Page {{ article_page.number }} of {{ paginator.num_pages }}</span>

                {% if article_page.has_next %}
                <li><a href="?page={{ article_page.next_page_number }}">Next</a></li>
                {% else %}
              <li><a href="#">Next</a></li>
                {% endif %}
            </ul>
          </nav>

        </div><!-- /.blog-main -->

        <div class="col-md-3 col-md-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4>Category</h4>

                  <ul>
                      {% for category in category %}
                  <li>
                      {{ category.category_name }}
                  </li>
                      {% endfor %}
                  </ul>

          </div>
          <div class="sidebar-module">

            <h4>Archives</h4>
            <ol class="list-unstyled">
              <li><a href="#"></a></li>
            </ol>

          </div>
          <div class="sidebar-module">
            <h4>Elsewhere</h4>
            <ol class="list-unstyled">
              <li><a href="#">GitHub</a></li>

            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
        <div class="col-md-4">
            <ul class="list-unstyled">
                <li>..........</li>
                <li>..........</li>
            </ul>
        </div>

        <div class="col-md-4 col-md-offset-4 text-right">
            <a href="#text-base">Back to top</a>
        </div>


    </footer>







{% endblock %}

templates/blog/article_detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}Article WoW{% endblock %}



{% block content %}

    <div class="jumbotron" id="detail-text" >
        <div class="container text-center">
            <h1>Article</h1>
            <h3>&emsp;&emsp;wondering.</h3>

        </div>
    </div>

    <div class="container">

        <div class="row">

            <div class="col-md-4 col-md-offset-1">
                <h1 id="article_title">{{ article.title }}</h1>
                <h3><span class="glyphicon glyphicon-user"></span> {{ article.author }}</h3>
{#                <a href="#"><span class="glyphicon glyphicon-edit"></span></a>#}
              {% if user.is_authenticated %}
                <a href="{% url 'edit' pk=article.pk %}"><span class="glyphicon glyphicon-edit"></span> </a>
                <a href="{% url 'delete' pk=article.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
              {% endif %}
            </div>
            <div class="col-md-6 " id="article_content">
                <p>{{ article.text }}</p>
            </div>
        </div>

        <hr>



{#            <a class="btn btn-default" href="{% url 'add_comment' pk=article.pk %}">Add comment</a>#}

        {% for comment in article.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
            <div class="comment">
                <div class="row">
                <div class="col-md-2 date">
                {{ comment.created_date }}
                    {% if not comment.approved_comment %}
                        <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}">
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                        <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}">
                            <span class="glyphicon glyphicon-ok"></span>
                        </a>
                    {% endif %}

                <strong>{{ comment.author }}</strong>
                </div>
                <div class="col-md-8">
                <p >{{ comment.text|linebreaks }}</p>
                </div>

            </div>
            <hr />
        </div>
        {% endif %}
        {% empty %}
            <p>No comments here yet.</p>
        {% endfor %}



    <hr />







    <div class="row">
        <div class="col-sm-4">
                <h3>What's wrong with you!</h3>
            <hr>
        <address>
        <strong>Email:</strong> <a href="mailto:#"> neon@domain.com</a><br><br>
        <strong>Phone:</strong> 1983
        </address>
            </div>

        <div class="col-sm-8 contact-form">

        <form id="contact" method="post" class="form" role="form">
             {% csrf_token %}
                <div class="row">
                <div class="col-xs-6 col-md-6 form-group">
                <input class="form-control" id="name" name="author" placeholder="Title" type="text" required autofocus />
            </div>
{#        <div class="col-xs-6 col-md-6 form-group">#}
{#            <input class="form-control" id="email" name="email" placeholder="Email" type="email" required />#}
{#        </div>#}
            </div>
        <textarea class="form-control" id="message" name="text" placeholder="Text" rows="5"></textarea>
        <br />
        <div class="row">

        <div class="col-xs-12 col-md-12 form-group">
        <button class="btn btn-primary pull-right" type="submit">Submit</button>
        </div>
        </div>
        </form>
    </div>
</div>

<hr />


</div>
























{% endblock %}

templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <title>{% block title %}{% endblock %}</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/article.css' %}">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--[if lt IE 9]>
			<script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
</head>

<body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top navbar-inverse" id="top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <span class="glyphicon glyphicon-tree-deciduous"></span>
            <a class="navbar-brand" href="#">Neon</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

            <li class="" id="homepage"><a href="{% url 'homepage' %}">
                <span class="glyphicon glyphicon-home"> Home</span></a></li>
            <li id="articlepage"><a href="{% url 'article' %}">Article</a></li>
            <li id="contactpage"><a href="{% url 'contact' %}">Contact</a></li>
            <li id="aboutpage"><a href="{% url 'about' %}">About</a></li>
          </ul>

      <!--    <form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
              </div>
              <button type="submit" class="btn btn-default">Submit</button>
          </form>
      -->

          <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="">Welcome {{ user.user }}</a> </li>
            <li><a href="{% url 'log_out' %}">Logout</a> </li>
            <li><a href="{% url 'set_password' %}">ChangePassword</a> </li>
          {% else %}
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-king " aria-hidden="true"></span>Login</a></li>
              <li><a href="{% url 'signup' %}"><span class="glyphicon glyphicon-queen " aria-hidden="true">Signup</span></a></li>
          {% endif %}

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>








    {% block content %}{% endblock %}













































<!--
    <footer class="footer container-fluid  ">
      <div class="container ">
          <div class="row">
              <div class="col-md-4 text-left">
                  <p>Hello World.</p>
                  <ul class="list-unstyled">
                      <li class="foot">Email:<a></a></li>
                      <li class="foot"></li>
                  </ul>
              </div>
          </div>
        <p class="text-muted">Place sticky footer content here.</p>
      </div>
    </footer>
-->



<script type="text/javascript">
    $('#{{active_menu}}').addClass("active");
</script>


</body>
</html>

templates/blog/edit.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}Edit Article{% endblock %}


{% block content %}


    <div class="jumbotron" id="text-base" >
        <div class="container text-center">
            <h1>Article</h1>
            <h3>&emsp;&emsp;Editing.</h3>

        </div>
    </div>

    <form method="POST" class="center-block">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                {{ form.as_p }}
                <button type="submit" class=" btn btn-default">Summit</button>
            </div>
        </div>


    </form>






























{% endblock %}

templates/blog/signup.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}Sign up{% endblock %}



{% block content %}






    <header class="jumbotron" id="header-base" >
        <div class="container text-center">
            <h1>My Blog</h1>
            <h3>&emsp;&emsp;Change the world.</h3>

        </div>
    </header>



    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
                {% if state == 'success' %}
                    <div class="well">
                        <h2 class="text-success text-center">注册成功！</h2>
                    </div>
                {% elif state == 'repeat_error' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码重复错误</h2>
                    </div>
                {% elif state == 'empty' %}
                    <div class="well">
                        <h2 class="text-warning text-center">密码不能为空</h2>
                    </div>
                {% elif state == 'user_exist' %}
                    <div class="well">
                        <h2 class="text-danger text-center">用户已经存在</h2>
                    </div>
                {% endif %}
                <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}
                    <h1 class="form-signin-heading text-center">请注册</h1>

                    <div class="form-group">
                        <label for="id_user_name" class="col-md-3 control-label">用户名：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" id="id_user_name" required name="username"
                                   autofocus>
                            <span class="help-block">用于登陆，可以包括大小写字母和下划线。</span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_name" class="col-md-3 control-label">昵称：</label>
                        <div class="col-md-9">
                            <input type="text" class="form-control" required name="nickname" id="id_name">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_passwd" class="col-md-3 control-label">密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="password" id="id_passwd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_repasswd" class="col-md-3 control-label">重复密码：</label>
                        <div class="col-md-9">
                            <input type="password" class="form-control" required name="repeat_password"
                                   id="id_repasswd">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="id_email" class="col-md-3 control-label">电子邮件：</label>
                        <div class="col-md-9">
                            <input type="email" class="form-control" required name="email" id="id_email">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-4 col-md-offset-4">
                            <button class="btn btn btn-primary btn-block" type="submit" id="id_submit">注册</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

{% endblock %}